apiVersion: v1
kind: ReplicationController
metadata:
  name: busybox-rs
  labels:
    app: busybox-rs
spec:
  replicas: 10
  selector:
    app: busybox-rs
  template:
    metadata:
      name: busybox-rs
      labels:
        app: busybox-rs
    spec:
      containers:
      - image: busybox
        command:
          - sleep
          - "30"
        imagePullPolicy: IfNotPresent
        name: busybox
      restartPolicy: Always
